### ISSUE TITLE
请问，第4点提到的代码生成器在哪里呢？

### ISSUE THREAD

**Issue by EverWang** [liuxx-u/bird-java#1]
4、实现从db->mappper->service->controller各层代码一键生成。

**Comment by liuxx-u** [comment]
bird-java/samples/bird-service-zero/bird-service-zero-impl/src/main/test/java/com/bird/service/zero/test/generator/CodeGenerator.java

生成出的文件，model文件需要一些小调整：
1、移除AbstractModal的泛型参数；
2、删除get，set方法自己生成下；

其他文件没问题。
